/**
 * Auto-generated type definitions for Nix packages
 * Generated from: /Users/tlamadon/git/nixts/src/homemanager/data/homemanager-options.json
 * Total packages: 70
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * Run 'npm run generate:types' to regenerate
 */

export type HomeManagerOptionName =
  | "home.enableNixpkgsReleaseCheck"
  | "home.file"
  | "home.homeDirectory"
  | "home.keyboard"
  | "home.language"
  | "home.packages"
  | "home.sessionPath"
  | "home.sessionVariables"
  | "home.stateVersion"
  | "home.username"
  | "programs.alacritty.enable"
  | "programs.bash.bashrcExtra"
  | "programs.bash.enable"
  | "programs.bash.initExtra"
  | "programs.bash.profileExtra"
  | "programs.bash.shellAliases"
  | "programs.direnv.enable"
  | "programs.emacs.enable"
  | "programs.fish.enable"
  | "programs.fish.shellAliases"
  | "programs.fish.shellInit"
  | "programs.fzf.enable"
  | "programs.git.aliases"
  | "programs.git.enable"
  | "programs.git.extraConfig"
  | "programs.git.ignores"
  | "programs.git.includes"
  | "programs.git.signing"
  | "programs.git.userEmail"
  | "programs.git.userName"
  | "programs.gpg.enable"
  | "programs.htop.enable"
  | "programs.kitty.enable"
  | "programs.neovim.defaultEditor"
  | "programs.neovim.enable"
  | "programs.neovim.extraConfig"
  | "programs.neovim.plugins"
  | "programs.neovim.viAlias"
  | "programs.neovim.vimAlias"
  | "programs.ssh.enable"
  | "programs.ssh.extraConfig"
  | "programs.ssh.matchBlocks"
  | "programs.starship.enable"
  | "programs.tmux.baseIndex"
  | "programs.tmux.clock24"
  | "programs.tmux.enable"
  | "programs.tmux.escapeTime"
  | "programs.tmux.extraConfig"
  | "programs.tmux.historyLimit"
  | "programs.tmux.keyMode"
  | "programs.tmux.plugins"
  | "programs.tmux.terminal"
  | "programs.vim.enable"
  | "programs.vim.extraConfig"
  | "programs.vim.plugins"
  | "programs.vim.settings"
  | "programs.vscode.enable"
  | "programs.zoxide.enable"
  | "programs.zsh.enable"
  | "programs.zsh.initExtra"
  | "programs.zsh.oh-my-zsh"
  | "programs.zsh.shellAliases"
  | "services.gpg-agent.defaultCacheTtl"
  | "services.gpg-agent.enable"
  | "services.gpg-agent.pinentryFlavor"
  | "xdg.cacheHome"
  | "xdg.configHome"
  | "xdg.dataHome"
  | "xdg.enable"
  | "xdg.stateHome";