/**
 * Auto-generated type definitions for Home Manager configuration
 * Generated from: /Users/tlamadon/git/nixts/src/homemanager/data/homemanager-options.json
 * Total options: 4701
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * Run 'npm run generate:homemanager:types' to regenerate
 */

// Main Home Manager configuration structure
export interface HomeManagerOptions {
  _module?: {
    args?: any;
  };
  accounts?: {
    calendar?: any;
    contact?: any;
    email?: any;
  };
  dbus?: {
    packages?: any;
  };
  dconf?: {
    settings?: any;
  };
  editorconfig?: {
    enable?: any;
    settings?: any;
  };
  fonts?: {
    fontconfig?: any;
  };
  gtk?: {
    colorScheme?: any;
    cursorTheme?: any;
    enable?: any;
    font?: any;
    gtk2?: any;
    gtk3?: any;
    gtk4?: any;
    iconTheme?: any;
    theme?: any;
  };
  home?: {
    activation?: any;
    checks?: any;
    enableDebugInfo?: any;
    enableNixpkgsReleaseCheck?: any;
    extraDependencies?: any;
    extraOutputsToInstall?: any;
    file?: any;
    homeDirectory?: any;
    keyboard?: any;
    language?: any;
    packages?: any;
    pointerCursor?: any;
    preferXdgDirectories?: any;
    profileDirectory?: any;
    sessionPath?: any;
    sessionSearchVariables?: any;
    sessionVariables?: any;
    shell?: any;
    shellAliases?: any;
    stateVersion?: any;
    username?: any;
  };
  i18n?: {
    glibcLocales?: any;
    inputMethod?: any;
  };
  launchd?: {
    agents?: any;
    enable?: any;
  };
  lib?: any;
  manual?: {
    html?: any;
    json?: any;
    manpages?: any;
  };
  meta?: {
    maintainers?: any;
  };
  news?: {
    display?: any;
  };
  nix?: {
    buildMachines?: any;
    channels?: any;
    checkConfig?: any;
    distributedBuilds?: any;
    extraOptions?: any;
    gc?: any;
    keepOldNixPath?: any;
    nixPath?: any;
    package?: any;
    registry?: any;
    settings?: any;
  };
  nixGL?: {
    defaultWrapper?: any;
    installScripts?: any;
    offloadWrapper?: any;
    packages?: any;
    prime?: any;
    vulkan?: any;
  };
  nixpkgs?: {
    config?: any;
    overlays?: any;
  };
  pam?: {
    sessionVariables?: any;
    yubico?: any;
  };
  programs?: {
    abaddon?: any;
    abook?: any;
    "acd-cli"?: any;
    aerc?: any;
    aerospace?: any;
    afew?: any;
    ahoviewer?: any;
    aiac?: any;
    aichat?: any;
    "aider-chat"?: any;
    airlift?: any;
    alacritty?: any;
    algia?: any;
    aliae?: any;
    alistral?: any;
    alot?: any;
    am2rlauncher?: any;
    amber?: any;
    amfora?: any;
    amoco?: any;
    amp?: any;
    andcli?: any;
    animdl?: any;
    "anime-downloader"?: any;
    anki?: any;
    anup?: any;
    "anvil-editor"?: any;
    anyrun?: any;
    aria2?: any;
    asciinema?: any;
    ashell?: any;
    astroid?: any;
    atuin?: any;
    autojump?: any;
    autorandr?: any;
    awscli?: any;
    bacon?: any;
    bash?: any;
    bashmount?: any;
    bat?: any;
    beets?: any;
    bemenu?: any;
    borgmatic?: any;
    bottom?: any;
    boxxy?: any;
    brave?: any;
    broot?: any;
    browserpass?: any;
    btop?: any;
    bun?: any;
    carapace?: any;
    cava?: any;
    cavalier?: any;
    chawan?: any;
    chromium?: any;
    "claude-code"?: any;
    "clock-rs"?: any;
    cmus?: any;
    codex?: any;
    "command-not-found"?: any;
    comodoro?: any;
    cudatext?: any;
    darcs?: any;
    delta?: any;
    desktoppr?: any;
    "diff-highlight"?: any;
    "diff-so-fancy"?: any;
    difftastic?: any;
    dircolors?: any;
    direnv?: any;
    discocss?: any;
    distrobox?: any;
    "docker-cli"?: any;
    earthly?: any;
    eclipse?: any;
    "element-desktop"?: any;
    emacs?: any;
    eww?: any;
    eza?: any;
    "fabric-ai"?: any;
    fastfetch?: any;
    fd?: any;
    feh?: any;
    firefox?: any;
    firefoxpwa?: any;
    fish?: any;
    floorp?: any;
    foliate?: any;
    foot?: any;
    formiko?: any;
    freetube?: any;
    fuzzel?: any;
    fzf?: any;
    "gallery-dl"?: any;
    gcc?: any;
    "gemini-cli"?: any;
    gh?: any;
    "gh-dash"?: any;
    ghostty?: any;
    git?: any;
    "git-cliff"?: any;
    "git-credential-keepassxc"?: any;
    "git-credential-oauth"?: any;
    "git-worktree-switcher"?: any;
    gitui?: any;
    glab?: any;
    "gnome-shell"?: any;
    "gnome-terminal"?: any;
    go?: any;
    goto?: any;
    gpg?: any;
    gradle?: any;
    granted?: any;
    grep?: any;
    "gurk-rs"?: any;
    halloy?: any;
    havoc?: any;
    helix?: any;
    hexchat?: any;
    himalaya?: any;
    "home-manager"?: any;
    hstr?: any;
    htop?: any;
    hwatch?: any;
    hyfetch?: any;
    hyprlock?: any;
    hyprpanel?: any;
    hyprshot?: any;
    "i3bar-river"?: any;
    i3blocks?: any;
    i3status?: any;
    "i3status-rust"?: any;
    iamb?: any;
    imv?: any;
    info?: any;
    inori?: any;
    "intelli-shell"?: any;
    ion?: any;
    irssi?: any;
    java?: any;
    "jetbrains-remote"?: any;
    jjui?: any;
    "joplin-desktop"?: any;
    joshuto?: any;
    jq?: any;
    jqp?: any;
    jrnl?: any;
    jujutsu?: any;
    k9s?: any;
    kakoune?: any;
    keepassxc?: any;
    keychain?: any;
    khal?: any;
    khard?: any;
    kickoff?: any;
    kitty?: any;
    kodi?: any;
    kraftkit?: any;
    kubecolor?: any;
    kubeswitch?: any;
    lapce?: any;
    lazydocker?: any;
    lazygit?: any;
    lazysql?: any;
    ledger?: any;
    less?: any;
    lesspipe?: any;
    lf?: any;
    librewolf?: any;
    lieer?: any;
    "looking-glass-client"?: any;
    lsd?: any;
    lutris?: any;
    man?: any;
    mangohud?: any;
    matplotlib?: any;
    mbsync?: any;
    mc?: any;
    mcfly?: any;
    meli?: any;
    mercurial?: any;
    mergiraf?: any;
    micro?: any;
    mise?: any;
    mods?: any;
    mpv?: any;
    mpvpaper?: any;
    mr?: any;
    msmtp?: any;
    mu?: any;
    mujmap?: any;
    "mullvad-vpn"?: any;
    mypy?: any;
    navi?: any;
    ncmpcpp?: any;
    ncspot?: any;
    ne?: any;
    neomutt?: any;
    neovide?: any;
    neovim?: any;
    newsboat?: any;
    nh?: any;
    nheko?: any;
    niriswitcher?: any;
    "nix-index"?: any;
    "nix-init"?: any;
    "nix-search-tv"?: any;
    "nix-your-shell"?: any;
    nnn?: any;
    noti?: any;
    notmuch?: any;
    numbat?: any;
    nushell?: any;
    nvchecker?: any;
    nyxt?: any;
    "obs-studio"?: any;
    obsidian?: any;
    offlineimap?: any;
    "oh-my-posh"?: any;
    onagre?: any;
    onedrive?: any;
    onlyoffice?: any;
    opam?: any;
    opencode?: any;
    openstackclient?: any;
    pandoc?: any;
    papis?: any;
    "password-store"?: any;
    patdiff?: any;
    "pay-respects"?: any;
    pazi?: any;
    pet?: any;
    pgcli?: any;
    pianobar?: any;
    pidgin?: any;
    pimsync?: any;
    pistol?: any;
    "piston-cli"?: any;
    pls?: any;
    poetry?: any;
    "powerline-go"?: any;
    pqiv?: any;
    ptyxis?: any;
    pubs?: any;
    pyenv?: any;
    pylint?: any;
    pywal?: any;
    qcal?: any;
    quickshell?: any;
    qutebrowser?: any;
    radicle?: any;
    "radio-active"?: any;
    "radio-cli"?: any;
    ranger?: any;
    rbenv?: any;
    rbw?: any;
    rclone?: any;
    readline?: any;
    retext?: any;
    riff?: any;
    rio?: any;
    ripgrep?: any;
    "ripgrep-all"?: any;
    rmpc?: any;
    rofi?: any;
    rtorrent?: any;
    ruff?: any;
    sagemath?: any;
    sapling?: any;
    satty?: any;
    sbt?: any;
    scmpuff?: any;
    "script-directory"?: any;
    senpai?: any;
    sesh?: any;
    sftpman?: any;
    sheldon?: any;
    sherlock?: any;
    sioyek?: any;
    sketchybar?: any;
    skim?: any;
    sm64ex?: any;
    smug?: any;
    "spotify-player"?: any;
    sqls?: any;
    ssh?: any;
    starship?: any;
    streamlink?: any;
    superfile?: any;
    swappy?: any;
    "sway-easyfocus"?: any;
    swayimg?: any;
    swaylock?: any;
    swayr?: any;
    taskwarrior?: any;
    tealdeer?: any;
    television?: any;
    terminator?: any;
    termite?: any;
    "tex-fmt"?: any;
    texlive?: any;
    thunderbird?: any;
    timidity?: any;
    tint2?: any;
    tiny?: any;
    tmate?: any;
    tmux?: any;
    todoman?: any;
    tofi?: any;
    topgrade?: any;
    "translate-shell"?: any;
    "tray-tui"?: any;
    trippy?: any;
    "twitch-tui"?: any;
    urxvt?: any;
    uv?: any;
    vdirsyncer?: any;
    vesktop?: any;
    vifm?: any;
    vim?: any;
    "vim-vint"?: any;
    vinegar?: any;
    visidata?: any;
    vivaldi?: any;
    vivid?: any;
    vscode?: any;
    wallust?: any;
    watson?: any;
    waveterm?: any;
    waybar?: any;
    waylogout?: any;
    wayprompt?: any;
    wezterm?: any;
    wleave?: any;
    wlogout?: any;
    wofi?: any;
    xmobar?: any;
    xplr?: any;
    yambar?: any;
    yarn?: any;
    yazi?: any;
    yofi?: any;
    "yt-dlp"?: any;
    "z-lua"?: any;
    zapzap?: any;
    zathura?: any;
    "zed-editor"?: any;
    zellij?: any;
    zk?: any;
    zoxide?: any;
    zsh?: any;
  };
  qt?: {
    enable?: any;
    kde?: any;
    platformTheme?: any;
    style?: any;
  };
  services?: {
    activitywatch?: any;
    amberol?: any;
    arrpc?: any;
    autorandr?: any;
    autotiling?: any;
    avizo?: any;
    batsignal?: any;
    betterlockscreen?: any;
    blanket?: any;
    "blueman-applet"?: any;
    borgmatic?: any;
    "cachix-agent"?: any;
    caffeine?: any;
    cbatticon?: any;
    clipcat?: any;
    cliphist?: any;
    clipman?: any;
    clipmenu?: any;
    clipse?: any;
    comodoro?: any;
    conky?: any;
    copyq?: any;
    darkman?: any;
    davmail?: any;
    devilspie2?: any;
    dropbox?: any;
    dunst?: any;
    "dwm-status"?: any;
    easyeffects?: any;
    emacs?: any;
    espanso?: any;
    "etesync-dav"?: any;
    flameshot?: any;
    fluidsynth?: any;
    fnott?: any;
    fusuma?: any;
    gammastep?: any;
    getmail?: any;
    "git-sync"?: any;
    glance?: any;
    "gnome-keyring"?: any;
    "gpg-agent"?: any;
    grobi?: any;
    "gromit-mpx"?: any;
    "home-manager"?: any;
    hound?: any;
    hypridle?: any;
    hyprpaper?: any;
    hyprpolkitagent?: any;
    hyprshell?: any;
    hyprsunset?: any;
    imapnotify?: any;
    jankyborders?: any;
    "jellyfin-mpv-shim"?: any;
    kanshi?: any;
    kbfs?: any;
    kdeconnect?: any;
    keybase?: any;
    keynav?: any;
    librespot?: any;
    lieer?: any;
    "linux-wallpaperengine"?: any;
    "listenbrainz-mpd"?: any;
    lorri?: any;
    ludusavi?: any;
    "lxqt-policykit-agent"?: any;
    "macos-remap-keys"?: any;
    mako?: any;
    mbsync?: any;
    megasync?: any;
    mopidy?: any;
    mpd?: any;
    "mpd-discord-rpc"?: any;
    "mpd-mpris"?: any;
    mpdris2?: any;
    mpdscribble?: any;
    "mpris-proxy"?: any;
    muchsync?: any;
    "network-manager-applet"?: any;
    "nextcloud-client"?: any;
    "notify-osd"?: any;
    ollama?: any;
    "opensnitch-ui"?: any;
    "osmscout-server"?: any;
    "owncloud-client"?: any;
    pantalaimon?: any;
    parcellite?: any;
    "pass-secret-service"?: any;
    pasystray?: any;
    pbgopy?: any;
    picom?: any;
    pimsync?: any;
    pizauth?: any;
    plan9port?: any;
    playerctld?: any;
    "plex-mpv-shim"?: any;
    podman?: any;
    "polkit-gnome"?: any;
    polybar?: any;
    poweralertd?: any;
    "protonmail-bridge"?: any;
    psd?: any;
    pueue?: any;
    pulseeffects?: any;
    radicle?: any;
    "random-background"?: any;
    recoll?: any;
    redshift?: any;
    remmina?: any;
    rescrobbled?: any;
    restic?: any;
    rsibreak?: any;
    safeeyes?: any;
    "screen-locker"?: any;
    sctd?: any;
    shikane?: any;
    shpool?: any;
    signaturepdf?: any;
    skhd?: any;
    snixembed?: any;
    spotifyd?: any;
    "ssh-agent"?: any;
    "ssh-tpm-agent"?: any;
    stalonetray?: any;
    "status-notifier-watcher"?: any;
    swayidle?: any;
    swaync?: any;
    swayosd?: any;
    swww?: any;
    sxhkd?: any;
    syncthing?: any;
    "systembus-notify"?: any;
    taffybar?: any;
    "tahoe-lafs"?: any;
    "tailscale-systray"?: any;
    "taskwarrior-sync"?: any;
    "tldr-update"?: any;
    trayer?: any;
    trayscale?: any;
    twmn?: any;
    udiskie?: any;
    unclutter?: any;
    unison?: any;
    vdirsyncer?: any;
    volnoti?: any;
    walker?: any;
    "way-displays"?: any;
    wayvnc?: any;
    "wl-clip-persist"?: any;
    wlsunset?: any;
    wluma?: any;
    wob?: any;
    wpaperd?: any;
    xcape?: any;
    "xembed-sni-proxy"?: any;
    xidlehook?: any;
    xscreensaver?: any;
    xsettingsd?: any;
    xsuspender?: any;
    "yubikey-agent"?: any;
  };
  specialisation?: any;
  systemd?: {
    user?: any;
  };
  targets?: {
    darwin?: any;
    genericLinux?: any;
  };
  uninstall?: any;
  vdirsyncer?: {
    auth?: any;
    authCert?: any;
    clientIdCommand?: any;
    clientSecretCommand?: any;
    collections?: any;
    conflictResolution?: any;
    enable?: any;
    itemTypes?: any;
    metadata?: any;
    partialSync?: any;
    postHook?: any;
    timeRange?: any;
    tokenFile?: any;
    urlCommand?: any;
    userAgent?: any;
    userNameCommand?: any;
    verify?: any;
    verifyFingerprint?: any;
  };
  wayland?: {
    systemd?: any;
    windowManager?: any;
  };
  xdg?: {
    autostart?: any;
    cacheFile?: any;
    cacheHome?: any;
    configFile?: any;
    configHome?: any;
    dataFile?: any;
    dataHome?: any;
    desktopEntries?: any;
    enable?: any;
    mime?: any;
    mimeApps?: any;
    portal?: any;
    stateFile?: any;
    stateHome?: any;
    systemDirs?: any;
    "terminal-exec"?: any;
    userDirs?: any;
  };
  xfconf?: {
    settings?: any;
  };
  xresources?: {
    extraConfig?: any;
    path?: any;
    properties?: any;
  };
  xsession?: {
    enable?: any;
    initExtra?: any;
    numlock?: any;
    pointerCursor?: any;
    preferStatusNotifierItems?: any;
    profileExtra?: any;
    profilePath?: any;
    scriptPath?: any;
    windowManager?: any;
  };
}

// Program-specific configuration types
export type ProgramName =
  | "abaddon"
  | "abook"
  | "acd-cli"
  | "aerc"
  | "aerospace"
  | "afew"
  | "ahoviewer"
  | "aiac"
  | "aichat"
  | "aider-chat"
  | "airlift"
  | "alacritty"
  | "algia"
  | "aliae"
  | "alistral"
  | "alot"
  | "am2rlauncher"
  | "amber"
  | "amfora"
  | "amoco"
  | "amp"
  | "andcli"
  | "animdl"
  | "anime-downloader"
  | "anki"
  | "anup"
  | "anvil-editor"
  | "anyrun"
  | "aria2"
  | "asciinema"
  | "ashell"
  | "astroid"
  | "atuin"
  | "autojump"
  | "autorandr"
  | "awscli"
  | "bacon"
  | "bash"
  | "bashmount"
  | "bat"
  | "beets"
  | "bemenu"
  | "borgmatic"
  | "bottom"
  | "boxxy"
  | "brave"
  | "broot"
  | "browserpass"
  | "btop"
  | "bun"
  | "carapace"
  | "cava"
  | "cavalier"
  | "chawan"
  | "chromium"
  | "claude-code"
  | "clock-rs"
  | "cmus"
  | "codex"
  | "command-not-found"
  | "comodoro"
  | "cudatext"
  | "darcs"
  | "delta"
  | "desktoppr"
  | "diff-highlight"
  | "diff-so-fancy"
  | "difftastic"
  | "dircolors"
  | "direnv"
  | "discocss"
  | "distrobox"
  | "docker-cli"
  | "earthly"
  | "eclipse"
  | "element-desktop"
  | "emacs"
  | "eww"
  | "eza"
  | "fabric-ai"
  | "fastfetch"
  | "fd"
  | "feh"
  | "firefox"
  | "firefoxpwa"
  | "fish"
  | "floorp"
  | "foliate"
  | "foot"
  | "formiko"
  | "freetube"
  | "fuzzel"
  | "fzf"
  | "gallery-dl"
  | "gcc"
  | "gemini-cli"
  | "gh-dash"
  | "gh"
  | "ghostty"
  | "git-cliff"
  | "git-credential-keepassxc"
  | "git-credential-oauth"
  | "git-worktree-switcher"
  | "git"
  | "gitui"
  | "glab"
  | "gnome-shell"
  | "gnome-terminal"
  | "go"
  | "goto"
  | "gpg"
  | "gradle"
  | "granted"
  | "grep"
  | "gurk-rs"
  | "halloy"
  | "havoc"
  | "helix"
  | "hexchat"
  | "himalaya"
  | "home-manager"
  | "hstr"
  | "htop"
  | "hwatch"
  | "hyfetch"
  | "hyprlock"
  | "hyprpanel"
  | "hyprshot"
  | "i3bar-river"
  | "i3blocks"
  | "i3status-rust"
  | "i3status"
  | "iamb"
  | "imv"
  | "info"
  | "inori"
  | "intelli-shell"
  | "ion"
  | "irssi"
  | "java"
  | "jetbrains-remote"
  | "jjui"
  | "joplin-desktop"
  | "joshuto"
  | "jq"
  | "jqp"
  | "jrnl"
  | "jujutsu"
  | "k9s"
  | "kakoune"
  | "keepassxc"
  | "keychain"
  | "khal"
  | "khard"
  | "kickoff"
  | "kitty"
  | "kodi"
  | "kraftkit"
  | "kubecolor"
  | "kubeswitch"
  | "lapce"
  | "lazydocker"
  | "lazygit"
  | "lazysql"
  | "ledger"
  | "less"
  | "lesspipe"
  | "lf"
  | "librewolf"
  | "lieer"
  | "looking-glass-client"
  | "lsd"
  | "lutris"
  | "man"
  | "mangohud"
  | "matplotlib"
  | "mbsync"
  | "mc"
  | "mcfly"
  | "meli"
  | "mercurial"
  | "mergiraf"
  | "micro"
  | "mise"
  | "mods"
  | "mpv"
  | "mpvpaper"
  | "mr"
  | "msmtp"
  | "mu"
  | "mujmap"
  | "mullvad-vpn"
  | "mypy"
  | "navi"
  | "ncmpcpp"
  | "ncspot"
  | "ne"
  | "neomutt"
  | "neovide"
  | "neovim"
  | "newsboat"
  | "nh"
  | "nheko"
  | "niriswitcher"
  | "nix-index"
  | "nix-init"
  | "nix-search-tv"
  | "nix-your-shell"
  | "nnn"
  | "noti"
  | "notmuch"
  | "numbat"
  | "nushell"
  | "nvchecker"
  | "nyxt"
  | "obs-studio"
  | "obsidian"
  | "offlineimap"
  | "oh-my-posh"
  | "onagre"
  | "onedrive"
  | "onlyoffice"
  | "opam"
  | "opencode"
  | "openstackclient"
  | "pandoc"
  | "papis"
  | "password-store"
  | "patdiff"
  | "pay-respects"
  | "pazi"
  | "pet"
  | "pgcli"
  | "pianobar"
  | "pidgin"
  | "pimsync"
  | "pistol"
  | "piston-cli"
  | "pls"
  | "poetry"
  | "powerline-go"
  | "pqiv"
  | "ptyxis"
  | "pubs"
  | "pyenv"
  | "pylint"
  | "pywal"
  | "qcal"
  | "quickshell"
  | "qutebrowser"
  | "radicle"
  | "radio-active"
  | "radio-cli"
  | "ranger"
  | "rbenv"
  | "rbw"
  | "rclone"
  | "readline"
  | "retext"
  | "riff"
  | "rio"
  | "ripgrep-all"
  | "ripgrep"
  | "rmpc"
  | "rofi"
  | "rtorrent"
  | "ruff"
  | "sagemath"
  | "sapling"
  | "satty"
  | "sbt"
  | "scmpuff"
  | "script-directory"
  | "senpai"
  | "sesh"
  | "sftpman"
  | "sheldon"
  | "sherlock"
  | "sioyek"
  | "sketchybar"
  | "skim"
  | "sm64ex"
  | "smug"
  | "spotify-player"
  | "sqls"
  | "ssh"
  | "starship"
  | "streamlink"
  | "superfile"
  | "swappy"
  | "sway-easyfocus"
  | "swayimg"
  | "swaylock"
  | "swayr"
  | "taskwarrior"
  | "tealdeer"
  | "television"
  | "terminator"
  | "termite"
  | "tex-fmt"
  | "texlive"
  | "thunderbird"
  | "timidity"
  | "tint2"
  | "tiny"
  | "tmate"
  | "tmux"
  | "todoman"
  | "tofi"
  | "topgrade"
  | "translate-shell"
  | "tray-tui"
  | "trippy"
  | "twitch-tui"
  | "urxvt"
  | "uv"
  | "vdirsyncer"
  | "vesktop"
  | "vifm"
  | "vim-vint"
  | "vim"
  | "vinegar"
  | "visidata"
  | "vivaldi"
  | "vivid"
  | "vscode"
  | "wallust"
  | "watson"
  | "waveterm"
  | "waybar"
  | "waylogout"
  | "wayprompt"
  | "wezterm"
  | "wleave"
  | "wlogout"
  | "wofi"
  | "xmobar"
  | "xplr"
  | "yambar"
  | "yarn"
  | "yazi"
  | "yofi"
  | "yt-dlp"
  | "z-lua"
  | "zapzap"
  | "zathura"
  | "zed-editor"
  | "zellij"
  | "zk"
  | "zoxide"
  | "zsh";

// Service-specific configuration types
export type ServiceName =
  | "activitywatch"
  | "amberol"
  | "arrpc"
  | "autorandr"
  | "autotiling"
  | "avizo"
  | "batsignal"
  | "betterlockscreen"
  | "blanket"
  | "blueman-applet"
  | "borgmatic"
  | "cachix-agent"
  | "caffeine"
  | "cbatticon"
  | "clipcat"
  | "cliphist"
  | "clipman"
  | "clipmenu"
  | "clipse"
  | "comodoro"
  | "conky"
  | "copyq"
  | "darkman"
  | "davmail"
  | "devilspie2"
  | "dropbox"
  | "dunst"
  | "dwm-status"
  | "easyeffects"
  | "emacs"
  | "espanso"
  | "etesync-dav"
  | "flameshot"
  | "fluidsynth"
  | "fnott"
  | "fusuma"
  | "gammastep"
  | "getmail"
  | "git-sync"
  | "glance"
  | "gnome-keyring"
  | "gpg-agent"
  | "grobi"
  | "gromit-mpx"
  | "home-manager"
  | "hound"
  | "hypridle"
  | "hyprpaper"
  | "hyprpolkitagent"
  | "hyprshell"
  | "hyprsunset"
  | "imapnotify"
  | "jankyborders"
  | "jellyfin-mpv-shim"
  | "kanshi"
  | "kbfs"
  | "kdeconnect"
  | "keybase"
  | "keynav"
  | "librespot"
  | "lieer"
  | "linux-wallpaperengine"
  | "listenbrainz-mpd"
  | "lorri"
  | "ludusavi"
  | "lxqt-policykit-agent"
  | "macos-remap-keys"
  | "mako"
  | "mbsync"
  | "megasync"
  | "mopidy"
  | "mpd-discord-rpc"
  | "mpd-mpris"
  | "mpd"
  | "mpdris2"
  | "mpdscribble"
  | "mpris-proxy"
  | "muchsync"
  | "network-manager-applet"
  | "nextcloud-client"
  | "notify-osd"
  | "ollama"
  | "opensnitch-ui"
  | "osmscout-server"
  | "owncloud-client"
  | "pantalaimon"
  | "parcellite"
  | "pass-secret-service"
  | "pasystray"
  | "pbgopy"
  | "picom"
  | "pimsync"
  | "pizauth"
  | "plan9port"
  | "playerctld"
  | "plex-mpv-shim"
  | "podman"
  | "polkit-gnome"
  | "polybar"
  | "poweralertd"
  | "protonmail-bridge"
  | "psd"
  | "pueue"
  | "pulseeffects"
  | "radicle"
  | "random-background"
  | "recoll"
  | "redshift"
  | "remmina"
  | "rescrobbled"
  | "restic"
  | "rsibreak"
  | "safeeyes"
  | "screen-locker"
  | "sctd"
  | "shikane"
  | "shpool"
  | "signaturepdf"
  | "skhd"
  | "snixembed"
  | "spotifyd"
  | "ssh-agent"
  | "ssh-tpm-agent"
  | "stalonetray"
  | "status-notifier-watcher"
  | "swayidle"
  | "swaync"
  | "swayosd"
  | "swww"
  | "sxhkd"
  | "syncthing"
  | "systembus-notify"
  | "taffybar"
  | "tahoe-lafs"
  | "tailscale-systray"
  | "taskwarrior-sync"
  | "tldr-update"
  | "trayer"
  | "trayscale"
  | "twmn"
  | "udiskie"
  | "unclutter"
  | "unison"
  | "vdirsyncer"
  | "volnoti"
  | "walker"
  | "way-displays"
  | "wayvnc"
  | "wl-clip-persist"
  | "wlsunset"
  | "wluma"
  | "wob"
  | "wpaperd"
  | "xcape"
  | "xembed-sni-proxy"
  | "xidlehook"
  | "xscreensaver"
  | "xsettingsd"
  | "xsuspender"
  | "yubikey-agent";
